---
- name: FQCN migration process
  ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration

  vars:
    upstream_name: amq_streams
    downstream_name: amq_streams
    downstream_namespace: redhat
    upstream_namespace: middleware_automation
    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') | default('https://github.com/ansible-middleware/amq_streams.git', true) }}"
    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') | default(omit) }}"
    gitdescribe_galaxy_version: "{{ true if lookup('env', 'RELEASE_NAME') == '' else false }}"
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
    post_processors_replacements:
     - match: "amq_streams_common_redhat_enabled: false"
       replace: "amq_streams_common_redhat_enabled: true"
     - match: "amq_streams_common_prereqs_dependencies: .*$"
       replace: "amq_streams_common_prereqs_dependencies: ['unzip']"
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_amq_streams
      homepage: https://access.redhat.com/products/red-hat-amq-streams
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    excluded_roles_from_downstream:
      - roles/amq_streams_exporter
    downstream_placeholder_delete:
      - build_status
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: galaxy_download
        content: |
          ### Installing the Collection from Automation Hub

          Before using the collection, you need to setup Ansible Automation Hub as galaxy server; then install it via the CLI:

              ansible-galaxy collection install redhat.amq_streams
      - placeholder: support
        content: |
          ## Support

          As Red Hat Ansible Certified Content, this collection is entitled to support through the Ansible Automation Platform (AAP) using the **Create issue** button on the top right corner.

          If a support case cannot be opened with Red Hat and the collection has been obtained either from Galaxy or GitHub, there may be community help available on the [Ansible Forum](https://forum.ansible.com/).
      - placeholder: rhn_credentials
        content: |
          #### Downloading from the Customer Portal

          The `amq_streams` role supports downloading and installing from the Red Hat Customer Portal using credentials associated to a service account. After having
          authenticated in the customer portal, navigate to the hybrid cloud console, and select the [services account tab](https://console.redhat.com/application-services/service-accounts)
          to create one, if needed. Client ID and Client Secret associated to the service account need to be provided to the collection using the following variables:
          ```
          rhn_username{{':'}} '<client_id>'
          rhn_password{{':'}} '<client_secret>'
          ```

          The downloaded product archive will be stored in the controller working directory, and then distributed to target nodes.
